# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MfxEJLLLLEBheH1Vpv4H1TVMH7Nnm8Z8

**program 2**
"""

def find_leap_years(given_year):

   count=0

   list_of_leap_years=[]

       

   while(count<15):

       if(given_year%4==0 or given_year%400==0 and given_year%100==0):

           list_of_leap_years.append(given_year)

           count=count+1

       given_year=given_year+1

   return list_of_leap_years

list_of_leap_years=find_leap_years(2000)

print(list_of_leap_years)

"""**program4**"""

def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

print( word_count('the quick brown fox jumps over the lazy dog.'))