# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYaAWyYbYjJqAOiy-zZT-VTgEZBuuIOe

**1.program to demonstrate basic data types is python**
"""

x = 5
print(x)
print(type(x))

x = "Hello World"
print(x)
print(type(x)) 

x = 20.5
print(x)
print(type(x)) 

x = 1j
print(x)
print(type(x)) 

x = ["apple", "banana", "cherry"]
print(x)
print(type(x))

x = ("apple", "banana", "cherry")
print(x)
print(type(x)) 

x = range(6)
print(x)
print(type(x)) 

x = {"name" : "John", "age" : 36}
print(x)
print(type(x)) 

x = {"apple", "banana", "cherry"}
print(x)
print(type(x)) 

x = frozenset({"apple", "banana", "cherry"})
print(x)
print(type(x)) 

x = True
print(x)
print(type(x)) 

x = b"Hello"
print(x)
print(type(x)) 

x = bytearray(5)
print(x)
print(type(x)) 

x = memoryview(bytes(5))
print(x)
print(type(x))

"""**2.program to print hello world**"""

x="hello world!"
print(x)

"""**3.program to print an integer(entered by the user)**"""

int=input("enter the number")
print(int)

"""**4.program to add two integers**"""

val1 =52
val2 =18
sum = float(val1) + float(val2)
print("The sum of given numbers is: ", sum)

"""**5.program to multiply two floating point numbers**"""

val1 = 50.2
val2 = 5.8
sum = float(val1) * float(val2)
print("The product of given numbers is: ", sum)

"""**6.program to compute quotient and remainder**"""

x =int(input("Enter the first number: "))
y =int(input("Enter the second number: "))
Quotient=x//y
Remainder=x%y
print("Quotient is:",Quotient)
print("Remainder is:",Remainder)

"""**7.program to swap two numbers**"""

x = input("enter the first number")
y = input("enter the second number")
temp = x
x = y
y = temp
print("The value of x is:", x)
print("The value of y is:", y)

"""**8.program to check whether a number is even or odd**"""

num = int(input("Enter a number: "))
if (num % 2) == 0:
   print("{0} is Even".format(num))
else:
   print("{0} is Odd".format(num))

"""**9.Program to check whether a character is vowel or consonant**"""

ch = input("Enter a character: ")
if(ch=='A' or ch=='a' or ch=='E' or ch =='e' or ch=='I'
 or ch=='i' or ch=='O' or ch=='o' or ch=='U' or ch=='u'):
    print(ch, "is a Vowel")
else:
    print(ch, "is a Consonant")

"""**10.program to find the largest number among three numbers**"""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: ")) 
if (num1 > num2) and (num1 > num3):
   largest = num1
elif (num2 > num1) and (num2 > num3):
   largest = num2
else:
   largest = num3 
print("The largest number is",largest)

"""**11.program to check leap year**"""

year = int(input("Enter a year: "))  
if (year % 4) == 0:  
   if (year % 100) == 0:  
       if (year % 400) == 0:  
           print("{0} is a leap year".format(year))  
       else:  
           print("{0} is not a leap year".format(year))  
   else:  
       print("{0} is a leap year".format(year))  
else:  
   print("{0} is not a leap year".format(year))

"""**12.program to check whether a number is positive or negative**"""

num = float(input("Enter a number: "))
if num > 0:
   print("Positive number")
elif num == 0:
   print("Zero")
else:
   print("Negative number")

"""**13.program to calculate the sum of natural numbers**"""

num = int(input("Enter a number: "))    
if num < 0:  
   print("Enter a positive number")  
else:  
   sum = 0  
   while(num > 0):  
       sum += num  
       num -= 1  
   print("The sum is",sum)

"""**14.program to find factorial of a number**"""

num = int(input("Enter a number: "))  
factorial = 1  
if num < 0:  
   print("Sorry, factorial does not exist for negative numbers")  
elif num == 0:  
   print("The factorial of 0 is 1")  
else:  
   for i in range(1,num + 1):  
       factorial = factorial*i  
   print("The factorial of",num,"is",factorial)

"""**15.program to generate multiplication table**"""

num = int(input("Show the multiplication table of? "))    
for i in range(1,11):  
   print(num,'x',i,'=',num*i)

"""**16.program to display fibonacci series**"""

nterms = int(input("How many terms you want? "))  
n1 = 0  
n2 = 1  
count = 2    
if nterms <= 0:  
   print("Plese enter a positive integer")  
elif nterms == 1:  
   print("Fibonacci sequence:")  
   print(n1)  
else:  
   print("Fibonacci sequence:")  
   print(n1,",",n2,end=', ')  
   while count < nterms:  
       nth = n1 + n2  
       print(nth,end=' , ')  
       n1 = n2  
       n2 = nth  
       count += 1

"""**17.program to find LCM of two numbers**"""

a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
if(a>b):
    min1=a
else:
    min1=b
while(1):
    if(min1%a==0 and min1%b==0):
        print("LCM is:",min1)
        break
    min1=min1+1

"""**18.program to count number of digits in an integer**"""

n=int(input("Enter number:"))
count=0
while(n>0):
    count=count+1
    n=n//10
print("The number of digits in the number are:",count)

"""**19.program to reverse a number**"""

number = int(input("Enter the integer number: "))  
revs_number = 0    
while (number > 0):    
    remainder = number % 10  
    revs_number = (revs_number * 10) + remainder  
    number = number // 10   
print("The reverse number is : {}".format(revs_number))

"""**20.program to calculate the power of a number**"""

number = int(input(" Please Enter any Positive Integer : "))
exponent = int(input(" Please Enter Exponent Value : "))
power = 1
for i in range(1, exponent + 1):
    power = power * number    
print("The Result of {0} Power {1} = {2}".format(number, exponent, power))

"""**21.program to check whether a number is palindrome or not**"""

n=int(input("Enter number:"))
temp=n
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10
if(temp==rev):
    print("The number is a palindrome!")
else:
    print("The number isn't a palindrome!")